import { Josefin_Sans, Mr_De_Haviland } from "next/font/google";
import "./globals.css";
import Header from "./(components)/header/Header";
import { ClerkProvider } from "@clerk/nextjs";
import FixedArrow from "./(components)/fixed-arrow/FixedArrow";
import Footer from "./(components)/footer/Footer";
import CartButtonProvider from "@/context/CartButtonContext";
import Overlay from "./(components)/overlay/Overlay";
import Cart from "./(components)/cart/Cart";
import { ReduxProvider } from "@/rtk/store";

const mrDeHaviland = Mr_De_Haviland({
  variable: "--font-cursive",
  subsets: ["latin"],
  weight: ["400"],
});
const josefin = Josefin_Sans({
  variable: "--font",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});
export const metadata = {
  title: "Beaux - Cosmo Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${josefin.className} ${mrDeHaviland.className} antialiased`}
        >
          <ReduxProvider>
            <CartButtonProvider>
              <Cart />
              <Overlay />
              <Header />
              <FixedArrow />
              {children}
              <Footer />
            </CartButtonProvider>
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
